services:
  db:
    image: mysql:8.0.44-debian
    container_name: ceidtrip-db
    environment:
      MYSQL_DATABASE: travel_agency
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./create_travel_agency_db.sql:/docker-entrypoint-initdb.d/01_create_db.sql
      - ./insert_travel_agency_db.sql:/docker-entrypoint-initdb.d/02_insert_db.sql
      - ./vehicle.sql:/docker-entrypoint-initdb.d/03_vehicles.sql
      - ./vehicle_inserts.sql:/docker-entrypoint-initdb.d/04_vehicle_insertions.sql
      - ./accomodation.sql:/docker-entrypoint-initdb.d/05_accomodation.sql
