services:
  db:
    image: mysql:lts
    container_name: ceidtrip-db
    restart: always
    environment:
      MYSQL_DATABASE: travel_agency
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ./source/database_schema:/scripts/1_creation:ro
      - ./source/triggers_scripts:/scripts/3_triggers:ro
      - ./source/database_seeding_scripts:/scripts/4_insertions:ro
      
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 60s
      
volumes:
  mysql_data:
